#spring:
#  jpa:
#    database: oracle
#      
#  datasource:
#    #数据源基本配置：
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle://localhost:1521/orcl
#    username: caolin
#    password: root123
#    #type: com.alibaba.druid.pool.DruidDataSource   
#    #数据源其他配置：

# freemarker相关配置
#spring:
#  freemarker:
#    request-context-attribute: req  #req访问request
#    suffix: .html  #后缀名
#    content-type: text/html
#    enabled: true
#    cache: false #缓存配置
#    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
#    charset: UTF-8 #编码格式
#    settings:
#      number_format: '0.##'   #数字格式化，无小数点